### ISSUE TITLE
Error with Elasticsearch

### ISSUE THREAD

**Issue by yaniv51** [steveny2k/docker-predictionio#5] opened 2017-12-07 14:36 UTC
First time with prediction IO and docker.

I tried to use with version 0.12:
$ docker run -it -p 8000:8000 steveny/predictionio:0.12.0 /bin/bash

While I'm trying to check status after using pio-start-all, I'm getting an error with elasticsearch:

[INFO] [Storage$] Verifying Meta Data Backend (Source: ELASTICSEARCH)...
[ERROR] [Management$] Unable to connect to all storage backends successfully.
The following shows the error message from the storage backend.

Connection refused (java.net.ConnectException)

Dumping configuration of initialized storage backend sources.
Please make sure they are correct.

Source Name: ELASTICSEARCH; Type: elasticsearch; Configuration: HOME -> /PredictionIO-0.12.0-incubating/vendors/elasticsearch-5.5.2, HOSTS -> localhost, PORTS -> 9200, CLUSTERNAME -> predictionio, TYPE -> elasticsearch

Did I missed something?

Thanks,
Yaniv

**Comment by Heluwe** [comment] 2017-12-08 06:36
I got the same problem

**Comment by adampl** [comment] 2017-12-14 19:29
me too :(

**Comment by steveny2k** [comment] 2017-12-15 20:17
Sorry for the issue. I will take a look.
It worked fine on my machine. Maybe the version I pushed was not right.

Anyone else tried that and found it works? thanks

**Comment by afanjul** [comment] 2017-12-20 23:31
Hi there, I have the same problem... 

`ERROR] [Management$] Unable to connect to all storage backends successfully.
The following shows the error message from the storage backend.

Connection refused (java.net.ConnectException)

Dumping configuration of initialized storage backend sources.
Please make sure they are correct.

Source Name: ELASTICSEARCH; Type: elasticsearch; Configuration: HOME -> /PredictionIO-0.12.0-incubating/vendors/elasticsearch-5.5.2, HOSTS -> localhost, PORTS -> 9200, CLUSTERNAME -> predictionio, TYPE -> elasticsearch`

When I do: `curl localhost:9200` it fails to connect, so it seems like Elasticsearch is no running, when I try to run it from the bin directory, it fails to start because is not possible to run elasticsearch as root... 

any solution?

**Comment by aczietlow** [comment] 2017-12-28 22:06
Making progress on this. Elasticsearch will *not* run as root user. I side stepped this by making a `pio` user and assigning permissions accordingly

**Comment by steveny2k** [comment] 2017-12-28 22:12
@aczietlow thanks a lot for debugging. could you make a Pull-Request and then i can merge your change to the code? thanks again.

**Comment by tgensol** [comment] 2018-01-04 15:47
Finally your changes are not working on my side, ES starts with pio-start-all but stops just after

**Comment by aczietlow** [comment] 2018-01-04 17:02
@tgensol Thanks for the feedback! I'll take a look and see if I can make another pass.

**Comment by farhanhu87** [comment] 2018-01-05 07:04
Hi,
Same issue with my side as well.
@steveny2k

**Comment by steveny2k** [comment] 2018-01-08 19:18
Thank you all for your feedback. I am trying out solutions.

**Comment by steveny2k** [comment] 2018-01-15 19:53
Sorry to all for slow progress due to busy schedules at work. 
Any update? @aczietlow @tgensol thanks a lot

**Comment by aczietlow** [comment] 2018-01-15 20:55
No worries. Same here to be honest. I should be able to update my PR in the next day or two.

**Comment by franmedmon** [comment] 2018-01-23 09:28
Same error here! Waiting for a solution guys...

**Comment by jyrkih** [comment] 2018-02-20 19:01
I think both Docker and Elasticsearch default to 2G RAM, so ES runs out of memory and gets killed. 
Maybe adding 
`ES_JAVA_OPTS="-Xms750m -Xmx750m"`
to pio-env.sh helps?

**Comment by steveny2k** [comment] 2018-02-20 21:37
@jyrkih thanks a lot for your suggestion. Could you try it on your machine and confirm it works for you? thanks

**Comment by jyrkih** [comment] 2018-02-21 08:23
Sure, tried over this PR and it works for me. Also run through the Product Engine Template quickstart just fine.

**Comment by steveny2k** [comment] 2018-02-21 08:31
nice, could you create a PR, I can then merge? thanks a lot @jyrkih

**Comment by steveny2k** [comment] 2018-02-24 08:45
@everyone 
thanks to everyone who reported issue and provided solution and PR, now the issue is resolved and new image has been pushed into docker public registry. 

Could you try pulling the new docker image to check if it works for you? thanks a lot 
`docker run -it -p 8000:8000 steveny/predictionio:0.12.0 /bin/bash`

**Comment by steveny2k** [comment] 2018-02-24 09:46
I will close this issue if no one reports the same issue after a week. Thanks everyone.

**Closed as completed** 2018-03-15 19:03 UTC
